name: pegasus_pdv
description: T2Ti ERP - Pegasus PDV

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version:A.B.C+X --> A.B.C represents the versionName such as 1.0.0 - X (the number after the +) represents the versionCode such as 1, 2, 3, etc.
version: 1.0.9+9

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.2
  intl: 0.19.0
  font_awesome_flutter: 10.7.0
  backdrop: 0.9.1
  http: 1.2.2
  #flutter_masked_text: any
  extended_masked_text: 3.0.1
  cpf_cnpj_validator: 2.0.0
  flutter_html: ^3.0.0-beta.2
  bottomreveal: 2.0.0
  flutter_barcode_scanner: 2.0.0
  flutter_bootstrap: 2.0.0
  #flutter_sparkline: any
  printing: ^5.13.2
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: 1.9.0
  awesome_dialog: 3.2.1
  image_picker: 1.1.2
  # catcher: 0.8.0
  sentry_flutter: ^8.7.0
  desktop_window: 0.4.0
  url_launcher: 6.3.0
  email_validator: 3.0.0
  flutter_dotenv: 5.1.0
  encrypt: 5.0.3
  bottom_navy_bar: 6.1.0
  flutter_spinbox: 0.13.1
  ini: 2.1.0
  custom_radio_grouped_button: 2.2.1
  csv: 6.0.0
  file_picker: 8.1.2
  crypto: 3.0.5
  share_plus: 10.0.2
  sparkline: 1.0.0
  platform_device_id: 1.0.1
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  catcher_2: ^1.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.1
  build_runner: 2.4.12
  msix: 3.16.8
  flutter_launcher_icons: 0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/
     - assets/text/
     - .env

msix_config:
  display_name: T2Ti Pegasus PDV
  publisher_display_name: T2Ti.COM
  identity_name: T2Ti.COM.T2TiPegasusPDV
  msix_version: 1.0.10.0
  publisher: CN=0A6E4754-6ACC-44ED-81F6-94B57BF2E8BC
  logo_path: C:\T2Ti ERP\ERP 3.0 Programas e Fontes\Flutter\pegasus_pdv\assets\images\logo_pegasus_pdv.png
  capabilities: internetClient,systemManagement,pointOfService,bluetooth
  store: true     
